name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features "cgmath,glam"
    - name: run clippy
      run: cargo clippy --verbose --features "cgmath,glam"
    - name: Run tests
      run: cargo test --verbose --features "cgmath,glam"
